"""Add 'undo_request' table

Revision ID: 03122a7ca711
Revises: 0bc44f8bba37
Create Date: 2018-11-05 16:40:20.104242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03122a7ca711'
down_revision = '0bc44f8bba37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('undo_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('response_time', sa.DateTime(), nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('still_actual', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('was_undone', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_undo_request_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_undo_request'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('undo_request')
    # ### end Alembic commands ###
