"""Add new *_enabled' columns in 'game' table, add 'chat_message' table

Revision ID: 0bc44f8bba37
Revises: f1b8fa1312af
Create Date: 2018-10-20 15:52:27.370601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc44f8bba37'
down_revision = 'f1b8fa1312af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('is_black', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_chat_message_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.add_column('game', sa.Column('chat_enabled', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('game', sa.Column('move_submit_enabled', sa.Boolean(), server_default='t', nullable=False))
    op.add_column('game', sa.Column('result', sa.String(length=6), nullable=True))
    op.add_column('game', sa.Column('undo_requests_enabled', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'undo_requests_enabled')
    op.drop_column('game', 'result')
    op.drop_column('game', 'move_submit_enabled')
    op.drop_column('game', 'chat_enabled')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
