"""Add game and move tables

Revision ID: f1b8fa1312af
Revises: 
Create Date: 2018-10-20 15:36:14.083522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b8fa1312af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_black', sa.String(length=32), nullable=False),
    sa.Column('link_white', sa.String(length=32), nullable=False),
    sa.Column('goban_size', sa.Integer(), server_default='9', nullable=False),
    sa.Column('move', sa.Integer(), server_default='0', nullable=False),
    sa.Column('finished', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_table('move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pass', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('x', sa.Integer(), server_default='0', nullable=False),
    sa.Column('y', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_move_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_move'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move')
    op.drop_table('game')
    # ### end Alembic commands ###
